/* Generated by the Systemtap dtrace wrapper */


#define _SDT_HAS_SEMAPHORES 1


#define STAP_HAS_SEMAPHORES 1 /* deprecated */


#include <sys/sdt.h>

/* RUBY_METHOD_ENTRY ( const char *, const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_METHOD_ENTRY_ENABLED() __builtin_expect (method__entry_semaphore, 0)
#define ruby_method__entry_semaphore method__entry_semaphore
#else
#define RUBY_METHOD_ENTRY_ENABLED() __builtin_expect (ruby_method__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_method__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_METHOD_ENTRY(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, method__entry, arg1, arg2, arg3, arg4)

/* RUBY_METHOD_RETURN ( const char *, const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_METHOD_RETURN_ENABLED() __builtin_expect (method__return_semaphore, 0)
#define ruby_method__return_semaphore method__return_semaphore
#else
#define RUBY_METHOD_RETURN_ENABLED() __builtin_expect (ruby_method__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_method__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_METHOD_RETURN(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, method__return, arg1, arg2, arg3, arg4)

/* RUBY_CMETHOD_ENTRY ( const char *, const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_CMETHOD_ENTRY_ENABLED() __builtin_expect (cmethod__entry_semaphore, 0)
#define ruby_cmethod__entry_semaphore cmethod__entry_semaphore
#else
#define RUBY_CMETHOD_ENTRY_ENABLED() __builtin_expect (ruby_cmethod__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_cmethod__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_CMETHOD_ENTRY(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, cmethod__entry, arg1, arg2, arg3, arg4)

/* RUBY_CMETHOD_RETURN ( const char *, const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_CMETHOD_RETURN_ENABLED() __builtin_expect (cmethod__return_semaphore, 0)
#define ruby_cmethod__return_semaphore cmethod__return_semaphore
#else
#define RUBY_CMETHOD_RETURN_ENABLED() __builtin_expect (ruby_cmethod__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_cmethod__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_CMETHOD_RETURN(arg1, arg2, arg3, arg4) \
DTRACE_PROBE4 (ruby, cmethod__return, arg1, arg2, arg3, arg4)

/* RUBY_REQUIRE_ENTRY ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_REQUIRE_ENTRY_ENABLED() __builtin_expect (require__entry_semaphore, 0)
#define ruby_require__entry_semaphore require__entry_semaphore
#else
#define RUBY_REQUIRE_ENTRY_ENABLED() __builtin_expect (ruby_require__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_require__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_REQUIRE_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, require__entry, arg1, arg2, arg3)

/* RUBY_REQUIRE_RETURN ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_REQUIRE_RETURN_ENABLED() __builtin_expect (require__return_semaphore, 0)
#define ruby_require__return_semaphore require__return_semaphore
#else
#define RUBY_REQUIRE_RETURN_ENABLED() __builtin_expect (ruby_require__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_require__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_REQUIRE_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, require__return, arg1, arg2, arg3)

/* RUBY_FIND_REQUIRE_ENTRY ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_FIND_REQUIRE_ENTRY_ENABLED() __builtin_expect (find__require__entry_semaphore, 0)
#define ruby_find__require__entry_semaphore find__require__entry_semaphore
#else
#define RUBY_FIND_REQUIRE_ENTRY_ENABLED() __builtin_expect (ruby_find__require__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_find__require__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_FIND_REQUIRE_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, find__require__entry, arg1, arg2, arg3)

/* RUBY_FIND_REQUIRE_RETURN ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_FIND_REQUIRE_RETURN_ENABLED() __builtin_expect (find__require__return_semaphore, 0)
#define ruby_find__require__return_semaphore find__require__return_semaphore
#else
#define RUBY_FIND_REQUIRE_RETURN_ENABLED() __builtin_expect (ruby_find__require__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_find__require__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_FIND_REQUIRE_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, find__require__return, arg1, arg2, arg3)

/* RUBY_LOAD_ENTRY ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_LOAD_ENTRY_ENABLED() __builtin_expect (load__entry_semaphore, 0)
#define ruby_load__entry_semaphore load__entry_semaphore
#else
#define RUBY_LOAD_ENTRY_ENABLED() __builtin_expect (ruby_load__entry_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_load__entry_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_LOAD_ENTRY(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, load__entry, arg1, arg2, arg3)

/* RUBY_LOAD_RETURN ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_LOAD_RETURN_ENABLED() __builtin_expect (load__return_semaphore, 0)
#define ruby_load__return_semaphore load__return_semaphore
#else
#define RUBY_LOAD_RETURN_ENABLED() __builtin_expect (ruby_load__return_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_load__return_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_LOAD_RETURN(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, load__return, arg1, arg2, arg3)

/* RUBY_RAISE ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_RAISE_ENABLED() __builtin_expect (raise_semaphore, 0)
#define ruby_raise_semaphore raise_semaphore
#else
#define RUBY_RAISE_ENABLED() __builtin_expect (ruby_raise_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_raise_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_RAISE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, raise, arg1, arg2, arg3)

/* RUBY_OBJECT_CREATE ( const char *, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_OBJECT_CREATE_ENABLED() __builtin_expect (object__create_semaphore, 0)
#define ruby_object__create_semaphore object__create_semaphore
#else
#define RUBY_OBJECT_CREATE_ENABLED() __builtin_expect (ruby_object__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_object__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_OBJECT_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, object__create, arg1, arg2, arg3)

/* RUBY_ARRAY_CREATE ( long, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_ARRAY_CREATE_ENABLED() __builtin_expect (array__create_semaphore, 0)
#define ruby_array__create_semaphore array__create_semaphore
#else
#define RUBY_ARRAY_CREATE_ENABLED() __builtin_expect (ruby_array__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_array__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_ARRAY_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, array__create, arg1, arg2, arg3)

/* RUBY_HASH_CREATE ( long, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_HASH_CREATE_ENABLED() __builtin_expect (hash__create_semaphore, 0)
#define ruby_hash__create_semaphore hash__create_semaphore
#else
#define RUBY_HASH_CREATE_ENABLED() __builtin_expect (ruby_hash__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_hash__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_HASH_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, hash__create, arg1, arg2, arg3)

/* RUBY_STRING_CREATE ( long, const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_STRING_CREATE_ENABLED() __builtin_expect (string__create_semaphore, 0)
#define ruby_string__create_semaphore string__create_semaphore
#else
#define RUBY_STRING_CREATE_ENABLED() __builtin_expect (ruby_string__create_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_string__create_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_STRING_CREATE(arg1, arg2, arg3) \
DTRACE_PROBE3 (ruby, string__create, arg1, arg2, arg3)

/* RUBY_PARSE_BEGIN ( const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_PARSE_BEGIN_ENABLED() __builtin_expect (parse__begin_semaphore, 0)
#define ruby_parse__begin_semaphore parse__begin_semaphore
#else
#define RUBY_PARSE_BEGIN_ENABLED() __builtin_expect (ruby_parse__begin_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_parse__begin_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_PARSE_BEGIN(arg1, arg2) \
DTRACE_PROBE2 (ruby, parse__begin, arg1, arg2)

/* RUBY_PARSE_END ( const char *, int ) */
#if defined STAP_SDT_V1
#define RUBY_PARSE_END_ENABLED() __builtin_expect (parse__end_semaphore, 0)
#define ruby_parse__end_semaphore parse__end_semaphore
#else
#define RUBY_PARSE_END_ENABLED() __builtin_expect (ruby_parse__end_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_parse__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_PARSE_END(arg1, arg2) \
DTRACE_PROBE2 (ruby, parse__end, arg1, arg2)

/* RUBY_INSN ( const char * ) */
#if defined STAP_SDT_V1
#define RUBY_INSN_ENABLED() __builtin_expect (insn_semaphore, 0)
#define ruby_insn_semaphore insn_semaphore
#else
#define RUBY_INSN_ENABLED() __builtin_expect (ruby_insn_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_insn_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_INSN(arg1) \
DTRACE_PROBE1 (ruby, insn, arg1)

/* RUBY_INSN_OPERAND ( const char *, const char * ) */
#if defined STAP_SDT_V1
#define RUBY_INSN_OPERAND_ENABLED() __builtin_expect (insn__operand_semaphore, 0)
#define ruby_insn__operand_semaphore insn__operand_semaphore
#else
#define RUBY_INSN_OPERAND_ENABLED() __builtin_expect (ruby_insn__operand_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_insn__operand_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_INSN_OPERAND(arg1, arg2) \
DTRACE_PROBE2 (ruby, insn__operand, arg1, arg2)

/* RUBY_GC_MARK_BEGIN ( ) */
#if defined STAP_SDT_V1
#define RUBY_GC_MARK_BEGIN_ENABLED() __builtin_expect (gc__mark__begin_semaphore, 0)
#define ruby_gc__mark__begin_semaphore gc__mark__begin_semaphore
#else
#define RUBY_GC_MARK_BEGIN_ENABLED() __builtin_expect (ruby_gc__mark__begin_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__mark__begin_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_GC_MARK_BEGIN() \
DTRACE_PROBE (ruby, gc__mark__begin)

/* RUBY_GC_MARK_END ( ) */
#if defined STAP_SDT_V1
#define RUBY_GC_MARK_END_ENABLED() __builtin_expect (gc__mark__end_semaphore, 0)
#define ruby_gc__mark__end_semaphore gc__mark__end_semaphore
#else
#define RUBY_GC_MARK_END_ENABLED() __builtin_expect (ruby_gc__mark__end_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__mark__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_GC_MARK_END() \
DTRACE_PROBE (ruby, gc__mark__end)

/* RUBY_GC_SWEEP_BEGIN ( ) */
#if defined STAP_SDT_V1
#define RUBY_GC_SWEEP_BEGIN_ENABLED() __builtin_expect (gc__sweep__begin_semaphore, 0)
#define ruby_gc__sweep__begin_semaphore gc__sweep__begin_semaphore
#else
#define RUBY_GC_SWEEP_BEGIN_ENABLED() __builtin_expect (ruby_gc__sweep__begin_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__sweep__begin_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_GC_SWEEP_BEGIN() \
DTRACE_PROBE (ruby, gc__sweep__begin)

/* RUBY_GC_SWEEP_END ( ) */
#if defined STAP_SDT_V1
#define RUBY_GC_SWEEP_END_ENABLED() __builtin_expect (gc__sweep__end_semaphore, 0)
#define ruby_gc__sweep__end_semaphore gc__sweep__end_semaphore
#else
#define RUBY_GC_SWEEP_END_ENABLED() __builtin_expect (ruby_gc__sweep__end_semaphore, 0)
#endif
__extension__ extern unsigned short ruby_gc__sweep__end_semaphore __attribute__ ((unused)) __attribute__ ((section (".probes")));
#define RUBY_GC_SWEEP_END() \
DTRACE_PROBE (ruby, gc__sweep__end)

